name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile: [activemodel6, activemodel7, activemodel8]
        ruby: [3.1, 3.2, 3.3, 3.4]
        exclude:
          - gemfile: activemodel6
            ruby: 3.4
          - gemfile: activemodel8
            ruby: 3.1
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
